apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-cm
spec:
  replicas: 4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: nginx-lp
          mountPath: /usr/share/nginx/html/
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: nginx-lp
        configMap:
          name: nginx-lp
          items:
          - key: page
            path: index.html
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf