apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-apache
  labels:
    app: php-apache
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: viejo/php-apache:health-check
        ports:
        - containerPort: 80
          name: apache-http
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        livenessProbe:
          httpGet:
            path: /healthy
            port: 80
        readinessProbe:
          httpGet:
            path: /healthy
            port: 80
        resources:
          requests:
            memory: "16M"
            cpu: "10m"
          limits:
            memory: "32M"
            cpu: "20m"
