kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/YOUR-NAME"
    
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume
  labels:
    app: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    securityContext:
      privileged: true
    ports:
    - containerPort: 80
      name: nginx-http
    volumeMounts:
    - name: nginx
      mountPath: /root/nginx-volume   # path in the pod
  volumes:
  - name: nginx
    hostPath:
      path: /var/YOUR-NAME             # path in the host machine