apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-apache
  labels:
    app: php-apache
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: php-apache
      name: php-apache
    spec:
      containers:
      - name: php-apache
        image: viejo/php-apache:health-check
        tty: true
        resources:
          requests:
            memory: "32M"
            cpu: "100m"
          limits:
            memory: "64M"
            cpu: "0.2"
        livenessProbe:
          httpGet:
            path: /health-check
            port: 80
            httpHeaders:
            - name: X-Custom-Header
              value: Ackstorm
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10