apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis
      command: ["redis-server"]
      args: ["/usr/local/etc/redis/redis.conf"]
      env:
      - name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis-pass
            key: password
      volumeMounts:
      - name: redis-volume
        mountPath: /usr/local/etc/redis/
  volumes:
    - name: redis-volume
      configMap:
        name: redis-config
        items:
        - key: pass
          path: redis.conf
  restartPolicy: Never